### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by tuffnatty** [farhan0581/django-admin-autocomplete-filter#7]
I see you've updated the license to LGPLv3 in setup.py, but kept GPLv3 in LICENSE. Could you please fix it?

**Comment by farhan0581** [comment]
fixed!

**Comment by andreymal** [comment]
@farhan0581 could you [replace the LICENSE file](https://www.gnu.org/licenses/gpl-howto.en.html) with [COPYING](https://www.gnu.org/licenses/gpl-3.0.txt) and [COPYING.LESSER](https://www.gnu.org/licenses/lgpl-3.0.txt) files? Without this, GitHub will show GPL instead of LGPL, whish is confusing.

Example of properly licensed repo: https://github.com/PyGithub/PyGithub

P.S. Why not BSD?

**Comment by xrmx** [comment]
@farhan0581 where did you fixed it? All the 3 branches on github have a GPL license in LICENSE.
